### ISSUE TITLE
The time is off by 3 hours

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Capstoneconnect#1]
I have found out that the time for the date is off by three hours so when I set the date for the students to do the evaluations the cut off is 9pm eastern time. Could that be corrected if it is not too much trouble?

**Comment by OptimusMaximus** [comment]
I fixed this for Dr. McCants almost two months ago.  I think he resent the email to you that he sent me two months ago.

**Comment by josemvidal** [comment]
Ok, I will close this. Thanks!
