### ISSUE TITLE
Add a way to open the evaluation back up or make it available again to the students after the date is past? 

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Capstoneconnect#2]
I had students do an evaluation and they reported this. Is there a way to open the evaluation back up or make it available again to the students after the date is past? Perhaps for the instance when a student for whatever reason, emergency, sickness ect. could not do it on the date due, than I could re-open for them to do their evaluation.

**Comment by OptimusMaximus** [comment]
This was already included in our final version.  I emailed him on how to reopen two months ago.  I think he sent the same email he sent me two months ago.  

For reopening an evaluation, you can always go to “Manage Evaluations” page and under “Closed Evaluations” you can open up the closed evaluation, put in a new date and time, and then click on “Update Evaluation” button.  This will allow you to open an evaluation back up for the students.

**Comment by josemvidal** [comment]
Ok. I'm closing this one too. Thanks!
